qimnet_crud_home:
    path: %qimnet.crud.path_prefix%/{configName}
    defaults:
        _controller: qimnet.crud.controller:indexAction
    methods: [GET]
    options: { expose: true }

qimnet_crud_index:
    path: %qimnet.crud.path_prefix%/{configName}/index/{page}/{sortField}/{sortDirection}
    requirements:
        page: '\d+'
        sortDirection: asc|desc
    defaults:
        _controller: qimnet.crud.controller:indexAction
        page: 1
        sortField: id
        sortDirection: desc
    methods: [GET]
    options: { expose: true }

qimnet_crud_new:
    path: %qimnet.crud.path_prefix%/{configName}/new
    defaults:
        _controller: qimnet.crud.controller:newAction
    methods: [GET,POST]
    options: { expose: true }

qimnet_crud_batch:
    path: %qimnet.crud.path_prefix%/{configName}/batch/{action}
    defaults:
        _controller: qimnet.crud.controller:batchAction
    methods: [POST]
    options: { expose: true }

qimnet_crud_delete:
    path: %qimnet.crud.path_prefix%/{configName}/{id}/delete
    defaults:
        _controller: qimnet.crud.controller:deleteAction
    methods: [POST]
    options: { expose: true }

qimnet_crud_filter:
    path: %qimnet.crud.path_prefix%/{configName}/filter
    defaults:
        _controller: qimnet.crud.controller:filterAction
    methods: [POST]
    options: { expose: true }

qimnet_crud_edit:
    path: %qimnet.crud.path_prefix%/{configName}/{id}/edit
    defaults:
        _controller: qimnet.crud.controller:editAction
    methods: [GET,POST]

qimnet_crud_show:
    path: %qimnet.crud.path_prefix%/{configName}/{id}
    defaults:
        _controller: qimnet.crud.controller:showAction
    options: { expose: true }
